<div id="map"></div>
<script type="text/javascript">// <![CDATA[
    var apiKey = '<?php echo $this->getConfig('key'); ?>';
    require([
        'LCB_GoogleMap/js/map'
    ], function (map) {
        map.render(
                document.getElementById('map'),
                <?php echo $this->getLatitude(); ?>,
                <?php echo $this->getLongitude(); ?>,
                <?php echo $block->getZoom(); ?>,
                '<?php echo ($block->getConfig('marker') ? $block->getMarker() : ''); ?>'
                );
    });
    // ]]>
</script>
